export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_FIXTERM=true

plugins=(
	autopep8
	celery
	django
	encode64
	fabric
	fbterm
	git
	jsontools
	last-working-dir
	npm
	pip
	python
	tmux
	virtualenvwrapper
)

source $ZSH/oh-my-zsh.sh
